version: '3'
services:
    influxdb:
        image: 'influxdb:latest'
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
    garie-securityheaders:
        image: 'garie-securityheaders:latest'
        ports:
            - 3000:3000
        environment:
            - HOST=influxdb
        depends_on:
            - influxdb
    chronograf:
        image: 'chronograf:latest'
        ports:
            - 8888:8888
        depends_on:
            - influxdb
